WITH RECURSIVE LEVEL_TABLE AS (
    SELECT ID, PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, L.LEVEL + 1
    FROM ECOLI_DATA E
    JOIN LEVEL_TABLE L
    ON L.ID = E.PARENT_ID
)

SELECT ID
FROM LEVEL_TABLE
WHERE LEVEL = 3
;