# IFNULL(LENGTH, 10) -> NULL인 경우 10으로 변환
# GREATEST(IFNULL(LENGTH, 10), 10) -> 변환된 값과 10 중에서 더 큰 값을 선택
# 즉, LENGTH가 10 이하이면 10이 되고, 10보다 크면 원래 값을 유지

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(GREATEST(IFNULL(LENGTH, 10), 10)) >= 33
ORDER BY FISH_TYPE;

SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(IFNULL(LENGTH, 10)) >= 33
ORDER BY FISH_TYPE;