SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY 
FROM ITEM_INFO AS A, ITEM_TREE AS B
WHERE A.ITEM_ID = B.ITEM_ID 
AND B.PARENT_ITEM_ID IN -- PARENT 가 있는 ITEM 찾기 
(SELECT ITEM_INFO.ITEM_ID FROM ITEM_INFO 
WHERE ITEM_INFO.RARITY = 'RARE')
ORDER BY A.ITEM_ID DESC;


-- # NULL 이 아닌것을 찾으려고 함.. 근데 질문 게시판 보니까 이러면 안된다네 ^^...
-- # 심지어 자꾸 엄청 많은 열이 나와서 중복도 제거해줌... 근데 이게 아님 ㅜㅜ!
-- # SELECT DISTINCT A.ITEM_ID, A.ITEM_NAME, A.RARITY 
-- # FROM ITEM_INFO AS A, ITEM_TREE AS B
-- # WHERE A.RARITY = 'RARE' OR B.PARENT_ITEM_ID IS NOT NULL 
-- # ORDER BY A.ITEM_ID DESC;