-- 아놔 개짜증 distinct 바깥에 써서 틀린거엿음 어쩐지 자쭈 99 나옴 ;;;
--SELECT DISTINCT COUNT(NAME) AS count FROM ANIMAL_INS
--WHERE NAME IS NOT NULL;

SELECT COUNT(DISTINCT NAME) AS count FROM ANIMAL_INS
WHERE NAME IS NOT NULL;