-- 실패 ..--
-- 내일 다시 도전 ... 어렵네 ㅜㅜ -- 
SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO
LEFT JOIN FISH_NAME_INFO
ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE FISH_INFO.FISH_TYPE = 'BASS' OR FISH_INFO.FISH_TYPE = 'SNAPPER'