-- 3월에 태어난 여성 목록 출력하기 
SELECT MEMBER_ID, MEMBER_NAME, GENDER, LEFT(DATE_OF_BIRTH, 10) AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '%-03-%' 
AND TLNO IS NOT NULL 
AND GENDER = 'W' -- 성별 부분을 빼먹어서 자꾸 틀림!!!! 
ORDER BY MEMBER_ID ASC;