-- 개어려운뎅 ...ㅎ?
-- 틀린 버전 ... 아놔 ON 으로 공통된 key 를 안 묶어 줘서 틀렷나바...그리고 where 을 reply 로 해서 .. ㅠ 어렵네.. 
-- 다시 풀어봐야할듯

-- SELECT BOARD.TITLE AS TITLE, 
-- BOARD.BOARD_ID AS BOARD_ID,
-- REPLY.REPLY_ID AS REPLY_ID,
-- REPLY.WRITER_ID AS WRITER_ID,
-- REPLY.CONTENTS AS CONTENTS,
-- DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
-- FROM USED_GOODS_BOARD AS BOARD
-- JOIN USED_GOODS_REPLY AS REPLY
-- WHERE REPLY.CREATED_DATE LIKE '2022-10%'
-- ORDER BY CREATED_DATE, TITLE ASC 

SELECT BOARD.TITLE AS TITLE, 
BOARD.BOARD_ID AS BOARD_ID,
REPLY.REPLY_ID AS REPLY_ID,
REPLY.WRITER_ID AS WRITER_ID,
REPLY.CONTENTS AS CONTENTS,
DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_REPLY AS REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE LIKE '2022-10%'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE ASC 