# 개빡쳐 앞에 주소 앞에 띄어쓰기 들어가서 자꾸 틀림 ;;;;; 열받
# SELECT 
# CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_FILE
# WHERE BOARD_ID = 
# (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)
# ORDER BY FILE_ID DESC;

SELECT 
CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY F.FILE_ID DESC;

# SELECT 
# CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_BOARD B
# JOIN USED_GOODS_FILE F
# ON B.BOARD_ID = F.BOARD_ID
# ORDER BY B.VIEWS DESC, F.FILE_ID DESC
# LIMIT 1;