SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E
ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
HAVING SUM(G.SCORE) = (
    SELECT MAX(TOTAL_SCORE) 
    FROM (
    SELECT SUM(G2.SCORE) AS TOTAL_SCORE
    FROM HR_GRADE G2
    GROUP BY G2.EMP_NO)    
    AS OTHER
);

SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E
ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
ORDER BY G.SCORE
LIMIT 1;