SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO I1
WHERE FAVORITES = (
    SELECT MAX(I2.FAVORITES)
    FROM REST_INFO I2
    WHERE I1.FOOD_TYPE = I2.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC
;