# 처음에 DATE_FORMAT 으로 해보려 함.. 하지만 안됨 ㅜㅜ ! 
# SELECT DATE_FORMAT(DATETIME, '%h') AS HOUR, COUNT(DATETIME) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY DATETIME
# ORDER BY DATETIME;

# HOUR 라는 함수를 쓰면 시만 나오나봐 검색했다.. ㅜ! 

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;