WITH JAN_SALES AS (
    SELECT BOOK_ID, SUM(SALES) AS SUM_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE * SUM_SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN JAN_SALES S ON S.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC