WITH MOST_FLAVOR AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
    ) AS SALES
    GROUP BY FLAVOR
    ORDER BY TOTAL DESC
    LIMIT 3
)

SELECT FLAVOR
FROM MOST_FLAVOR
;