-- a는 자식, b는 부모로 selfjoin 진행
SELECT a.ID, a.GENOTYPE, b.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA a
JOIN ECOLI_DATA b
ON a.PARENT_ID = b.ID
WHERE (a.GENOTYPE | b.GENOTYPE) = a.GENOTYPE
ORDER BY a.ID;