SELECT a.CATEGORY, SUM(b.SALES) AS TOTAL_SALES
FROM BOOK a
JOIN BOOK_SALES b
ON a.BOOK_ID = b.BOOK_ID
WHERE b.SALES_DATE BETWEEN '2022-01-01' and '2022-01-31'
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY ASC;