WITH PY AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
), C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
), FRONT AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), GRADE_TB AS (
    SELECT
        CASE
            WHEN (SKILL_CODE & (SELECT CODE FROM PY)) > 0 AND (SKILL_CODE & (SELECT CODE FROM FRONT)) > 0 THEN 'A'
            WHEN (SKILL_CODE & (SELECT CODE FROM C)) > 0 THEN 'B'
            WHEN (SKILL_CODE & (SELECT CODE FROM FRONT)) > 0 THEN 'C'
        END AS GRADE,
        ID, EMAIL
    FROM DEVELOPERS
)

SELECT *
FROM GRADE_TB
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
;