# 재귀로 0 ~ 23 만들어주는거 아래 코드
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS
    WHERE HOUR < 23)
SELECT H.HOUR AS HOUR, COUNT(O.DATETIME) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS O
ON HOUR(O.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR
