SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN ( # 2세대가 부모 id인 거 찾기 (=3세대)
SELECT ID 
FROM ECOLI_DATA
WHERE PARENT_ID IN ( # 1세대가 부모 id인 거 찾기 (=2세대)
SELECT ID 
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL) # 1세대 찾기  
)
ORDER BY ID;