-- 조건에 부합하는 중고거래 댓글 조회하기
SELECT
USED_GOODS_BOARD.TITLE,
USED_GOODS_BOARD.BOARD_ID,
USED_GOODS_REPLY.REPLY_ID, 
USED_GOODS_REPLY.WRITER_ID, 
USED_GOODS_REPLY.CONTENTS, 
LEFT(USED_GOODS_REPLY.CREATED_DATE,10) AS CREATED_DATE
FROM USED_GOODS_BOARD
JOIN USED_GOODS_REPLY 
ON USED_GOODS_REPLY.BOARD_ID = USED_GOODS_BOARD.BOARD_ID
WHERE USED_GOODS_BOARD.CREATED_DATE LIKE '2022-10%'
-- 2022-10 게시글인데 댓글로 찾아서 계속 틀림 ㅜㅜ
ORDER BY USED_GOODS_REPLY.CREATED_DATE ASC, USED_GOODS_BOARD.TITLE ASC