-- 서브쿼리 사용
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)

-- ORDER BY LIMIT 사용
# 상수가 알려줬던 방법 근데 조건문으로 가져오고싶어서 위에 방법 찾아봄
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC LIMIT 1