-- 코드를 입력하세요
SELECT 
    CASE
        WHEN PRODUCT_ID IN (1, 2) THEN 'A1'
        WHEN PRODUCT_ID IN (3, 4, 5) THEN 'C3'
        WHEN PRODUCT_ID IN (6) THEN 'K1'
    END AS CATEGORY,
    COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY

# 지피티한테 물어봄 먼소린지 몰겠음 심지어 답 안나옴 넘 잠와